name:                template-haskell-reload
version:             0.0.0.0
github:              "NorfairKing/template-haskell-reload"
license:             AllRightsReserved
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2020 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - bytestring
  - conduit
  - containers
  - path
  - path-io
  - template-haskell
  - text

tests:
  template-haskell-reload-test:
    main:                Spec.hs
    source-dirs:         test
    build-tools:         hspec-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - hspec
    - path
    - template-haskell-reload
    - text
